
import __ASTRO_IMAGE_IMPORT_HLe3X from "./Adrian.JPG?astroContentImageFlag=&importer=src%2Fcontent%2Fteam%2Fadrian-sexauer.md";
import __ASTRO_IMAGE_IMPORT_ZPio4p from "./enzio.png?astroContentImageFlag=&importer=src%2Fcontent%2Fteam%2Fenzio-maggiore.md";
import __ASTRO_IMAGE_IMPORT_Z1tEJpk from "./fabio.JPG?astroContentImageFlag=&importer=src%2Fcontent%2Fteam%2Ffabio-schneider.md";
import __ASTRO_IMAGE_IMPORT_ZSvqkI from "./Dino.JPG?astroContentImageFlag=&importer=src%2Fcontent%2Fteam%2Fdino-saggiomo.md";
import __ASTRO_IMAGE_IMPORT_Z1btbSz from "./Yannick.JPG?astroContentImageFlag=&importer=src%2Fcontent%2Fteam%2Fyannick-lawson.md";
import __ASTRO_IMAGE_IMPORT_gpPbz from "./pics/infoabend2602.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Finfoabend-padel.md";
import __ASTRO_IMAGE_IMPORT_Z27ucNO from "./Jana.JPG?astroContentImageFlag=&importer=src%2Fcontent%2Fteam%2Fjana-koppermann.md";
import __ASTRO_IMAGE_IMPORT_SJYIL from "./matthias.png?astroContentImageFlag=&importer=src%2Fcontent%2Fteam%2Fmatthias-loeffler.md";
export default new Map([["./Adrian.JPG?astroContentImageFlag=&importer=src%2Fcontent%2Fteam%2Fadrian-sexauer.md", __ASTRO_IMAGE_IMPORT_HLe3X], ["./enzio.png?astroContentImageFlag=&importer=src%2Fcontent%2Fteam%2Fenzio-maggiore.md", __ASTRO_IMAGE_IMPORT_ZPio4p], ["./fabio.JPG?astroContentImageFlag=&importer=src%2Fcontent%2Fteam%2Ffabio-schneider.md", __ASTRO_IMAGE_IMPORT_Z1tEJpk], ["./Dino.JPG?astroContentImageFlag=&importer=src%2Fcontent%2Fteam%2Fdino-saggiomo.md", __ASTRO_IMAGE_IMPORT_ZSvqkI], ["./Yannick.JPG?astroContentImageFlag=&importer=src%2Fcontent%2Fteam%2Fyannick-lawson.md", __ASTRO_IMAGE_IMPORT_Z1btbSz], ["./pics/infoabend2602.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Finfoabend-padel.md", __ASTRO_IMAGE_IMPORT_gpPbz], ["./Jana.JPG?astroContentImageFlag=&importer=src%2Fcontent%2Fteam%2Fjana-koppermann.md", __ASTRO_IMAGE_IMPORT_Z27ucNO], ["./matthias.png?astroContentImageFlag=&importer=src%2Fcontent%2Fteam%2Fmatthias-loeffler.md", __ASTRO_IMAGE_IMPORT_SJYIL]]);
		